server_2.obj : error LNK2019: __imp__accept@12_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__bind@12_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__closesocket@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__htonl@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__htons@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__recv@16_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__send@16_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__socket@12_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__WSAStartup@8_main 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: __imp__WSACleanup@0_ErrorHandling 함수에서 참조되는 확인할 수 없는 외부 기호
server_2.obj : error LNK2019: _inetntoa_main 함수에서 참조되는 확인할 수 없는 외부 기호
C:\Users\newcy\source\repos\sock_trans_serv\Debug\sock_trans_serv.exe : fatal error LNK1120: 11개의 확인할 수 없는 외부 참조입니다.
